version: '3.8'

services:
  api:
    container_name: adminspace-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3009:3000"
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - adminspace-network

  postgres:
    container_name: adminspace-postgres
    image: postgres:14-alpine
    networks:
      - adminspace-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    # ports:  # Comentamos o eliminamos esta línea
    #   - "5433:5432"  # Y esta también
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  adminspace-network:

volumes:
  postgres-data: