version: '3.8'

services:
  api:
    container_name: adminspace-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3009:3000"
    command: >
      sh -c "
        echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf &&
        NODE_OPTIONS=--dns-result-order=ipv4first npm run start:dev
      "
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    networks:
      - adminspace-network
    dns:
      - 8.8.8.8  # Servidor DNS de Google primario
      - 8.8.4.4  # Servidor DNS de Google secundario
    restart: always

networks:
  adminspace-network:
    driver: bridge